# Generated by Django 4.0.5 on 2022-07-08 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityRequest',
            fields=[
                ('universityarticle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.universityarticle')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('university_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='article.universityarticle')),
            ],
            bases=('article.universityarticle',),
        ),
        migrations.CreateModel(
            name='TeacherRequest',
            fields=[
                ('teacherarticle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.teacherarticle')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teacher_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='article.teacherarticle')),
            ],
            bases=('article.teacherarticle',),
        ),
    ]
