version: "3"

services:
    database:
        container_name: database
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: dbName
            POSTGRES_USER: dbUser
            POSTGRES_PASSWORD: dbPassword
