# Generated by Django 4.0.5 on 2022-07-08 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislike',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comment.commentrating'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comment.commentrating'),
        ),
    ]
